"""create question tables

Revision ID: 001
Revises: 
Create Date: 2024-01-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uid', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('question_sessions',
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('uid', sa.String(length=255), nullable=True),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('user_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('uid', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('period_description', sa.String(length=100), nullable=True),
    sa.Column('birth_control', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('last_period_date', sa.String(length=50), nullable=True),
    sa.Column('cycle_length', sa.String(length=50), nullable=True),
    sa.Column('period_concerns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('body_concerns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('skin_hair_concerns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mental_health_concerns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('other_concerns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('top_concern', sa.String(length=255), nullable=True),
    sa.Column('diagnosed_conditions', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_responses_id'), 'user_responses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_responses_id'), table_name='user_responses')
    op.drop_table('user_responses')
    op.drop_table('question_sessions')
    op.drop_table('users')
    # ### end Alembic commands ### 