"""convert_to_utc_based_timezone_system

Revision ID: 04bd3784e1e7
Revises: 919a7c5c78da
Create Date: 2025-08-23 03:24:08.706521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04bd3784e1e7'
down_revision: Union[str, None] = '919a7c5c78da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_sessions', sa.Column('last_period_date_utc', sa.DateTime(), nullable=True))
    op.drop_column('question_sessions', 'last_period_date')
    op.add_column('user_profiles', sa.Column('current_timezone', sa.String(length=50), nullable=True))
    op.add_column('user_responses', sa.Column('last_period_date_utc', sa.DateTime(), nullable=True))
    op.add_column('user_responses', sa.Column('survey_timezone', sa.String(length=50), nullable=True))
    op.drop_column('user_responses', 'last_period_date')
    op.drop_column('user_responses', 'current_timezone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_responses', sa.Column('current_timezone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('user_responses', sa.Column('last_period_date', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('user_responses', 'survey_timezone')
    op.drop_column('user_responses', 'last_period_date_utc')
    op.drop_column('user_profiles', 'current_timezone')
    op.add_column('question_sessions', sa.Column('last_period_date', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('question_sessions', 'last_period_date_utc')
    # ### end Alembic commands ###
