"""remove_frequency_parsed_and_update_duration_weeks

Revision ID: 0ac131da102e
Revises: 9d56876a1010
Create Date: 2025-08-20 18:48:50.768762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ac131da102e'
down_revision: Union[str, None] = '9d56876a1010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First clean up existing data (extract numbers from strings)
    op.execute("UPDATE recommendation_records SET duration_weeks = NULL WHERE duration_weeks IS NOT NULL AND duration_weeks !~ '^[0-9]+$'")
    
    # Use USING clause for type conversion
    op.execute("ALTER TABLE recommendation_records ALTER COLUMN duration_weeks TYPE INTEGER USING duration_weeks::INTEGER")
    
    op.drop_column('recommendation_records', 'frequency_parsed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendation_records', sa.Column('frequency_parsed', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column('recommendation_records', 'duration_weeks',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###
