"""add_recommendation_redistribution_table

Revision ID: 19178993c4aa
Revises: a39aaace7e05
Create Date: 2025-08-21 20:18:58.528696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '19178993c4aa'
down_revision: Union[str, None] = 'a39aaace7e05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_redistributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=255), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('original_date', sa.Date(), nullable=False),
    sa.Column('redistributed_dates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('redistribution_reason', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendation_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uid'], ['user_profiles.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_redistribution_date', 'recommendation_redistributions', ['original_date'], unique=False)
    op.create_index('idx_redistribution_user_rec', 'recommendation_redistributions', ['uid', 'recommendation_id'], unique=False)
    op.create_index(op.f('ix_recommendation_redistributions_id'), 'recommendation_redistributions', ['id'], unique=False)
    op.create_index(op.f('ix_recommendation_redistributions_original_date'), 'recommendation_redistributions', ['original_date'], unique=False)
    op.create_index(op.f('ix_recommendation_redistributions_recommendation_id'), 'recommendation_redistributions', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_recommendation_redistributions_uid'), 'recommendation_redistributions', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendation_redistributions_uid'), table_name='recommendation_redistributions')
    op.drop_index(op.f('ix_recommendation_redistributions_recommendation_id'), table_name='recommendation_redistributions')
    op.drop_index(op.f('ix_recommendation_redistributions_original_date'), table_name='recommendation_redistributions')
    op.drop_index(op.f('ix_recommendation_redistributions_id'), table_name='recommendation_redistributions')
    op.drop_index('idx_redistribution_user_rec', table_name='recommendation_redistributions')
    op.drop_index('idx_redistribution_date', table_name='recommendation_redistributions')
    op.drop_table('recommendation_redistributions')
    # ### end Alembic commands ###
