"""add recommendation_records table

Revision ID: 201294a9bf6c
Revises: d1bfdfd82071
Create Date: 2025-08-19 15:22:37.447188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '201294a9bf6c'
down_revision: Union[str, None] = 'd1bfdfd82071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=255), nullable=False),
    sa.Column('recommendation_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('specific_action', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('contraindications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('conditions', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('symptoms', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('hormones', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('food_amount', sa.String(length=100), nullable=True),
    sa.Column('food_item', sa.String(length=200), nullable=True),
    sa.Column('exercise_duration', sa.String(length=100), nullable=True),
    sa.Column('exercise_type', sa.String(length=200), nullable=True),
    sa.Column('exercise_intensity', sa.String(length=100), nullable=True),
    sa.Column('mindfulness_duration', sa.String(length=100), nullable=True),
    sa.Column('mindfulness_technique', sa.String(length=200), nullable=True),
    sa.Column('frequency_detail', sa.String(length=100), nullable=True),
    sa.Column('duration_weeks', sa.String(length=100), nullable=True),
    sa.Column('research_summary', sa.Text(), nullable=True),
    sa.Column('research_studies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_profile_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_records_id'), 'recommendation_records', ['id'], unique=False)
    op.create_index(op.f('ix_recommendation_records_uid'), 'recommendation_records', ['uid'], unique=False)
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uid', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('display_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('uid', name=op.f('users_pkey'))
    )
    op.drop_index(op.f('ix_recommendation_records_uid'), table_name='recommendation_records')
    op.drop_index(op.f('ix_recommendation_records_id'), table_name='recommendation_records')
    op.drop_table('recommendation_records')
    # ### end Alembic commands ###
