"""refactor session schema new

Revision ID: 2c0cc15be40b
Revises: refactor_session_schema
Create Date: 2025-08-15 21:55:45.567999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c0cc15be40b'
down_revision: Union[str, None] = 'refactor_session_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question_sessions', 'device_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_index(op.f('ix_question_sessions_session_id'), 'question_sessions', ['session_id'], unique=False)
    op.add_column('user_responses', sa.Column('age', sa.Integer(), nullable=True))
    op.alter_column('user_responses', 'uid',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_index(op.f('ix_user_responses_uid'), 'user_responses', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_responses_uid'), table_name='user_responses')
    op.alter_column('user_responses', 'uid',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('user_responses', 'age')
    op.drop_index(op.f('ix_question_sessions_session_id'), table_name='question_sessions')
    op.alter_column('question_sessions', 'device_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
