"""add_new_scheduling_tables

Revision ID: 414c6668933f
Revises: 19178993c4aa
Create Date: 2025-08-21 20:40:48.947474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '414c6668933f'
down_revision: Union[str, None] = '19178993c4aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_schedules',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uid', sa.String(length=255), nullable=False),
    sa.Column('tzid', sa.String(length=100), nullable=False),
    sa.Column('rrule', sa.String(length=500), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_emitted_local_date', sa.Date(), nullable=True),
    sa.Column('next_fire_at_utc', sa.DateTime(), nullable=True),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendation_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uid'], ['user_profiles.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_schedule_next_fire', 'recommendation_schedules', ['next_fire_at_utc'], unique=False)
    op.create_index('idx_schedule_user_active', 'recommendation_schedules', ['uid', 'is_active'], unique=False)
    op.create_index(op.f('ix_recommendation_schedules_id'), 'recommendation_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_recommendation_schedules_uid'), 'recommendation_schedules', ['uid'], unique=False)
    op.create_table('daily_assignments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uid', sa.String(length=255), nullable=False),
    sa.Column('schedule_id', sa.BigInteger(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('assignment_date', sa.Date(), nullable=False),
    sa.Column('time_group', sa.String(length=50), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendation_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['recommendation_schedules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uid'], ['user_profiles.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assignment_schedule_date', 'daily_assignments', ['schedule_id', 'assignment_date'], unique=False)
    op.create_index('idx_assignment_user_date', 'daily_assignments', ['uid', 'assignment_date'], unique=False)
    op.create_index(op.f('ix_daily_assignments_assignment_date'), 'daily_assignments', ['assignment_date'], unique=False)
    op.create_index(op.f('ix_daily_assignments_id'), 'daily_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_daily_assignments_recommendation_id'), 'daily_assignments', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_daily_assignments_schedule_id'), 'daily_assignments', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_daily_assignments_uid'), 'daily_assignments', ['uid'], unique=False)
    op.create_table('schedule_redistributions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('schedule_id', sa.BigInteger(), nullable=False),
    sa.Column('original_date', sa.Date(), nullable=False),
    sa.Column('override_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['recommendation_schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_redistribution_dates', 'schedule_redistributions', ['original_date', 'override_date'], unique=False)
    op.create_index('idx_redistribution_schedule', 'schedule_redistributions', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_schedule_redistributions_id'), 'schedule_redistributions', ['id'], unique=False)
    op.create_index(op.f('ix_schedule_redistributions_schedule_id'), 'schedule_redistributions', ['schedule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedule_redistributions_schedule_id'), table_name='schedule_redistributions')
    op.drop_index(op.f('ix_schedule_redistributions_id'), table_name='schedule_redistributions')
    op.drop_index('idx_redistribution_schedule', table_name='schedule_redistributions')
    op.drop_index('idx_redistribution_dates', table_name='schedule_redistributions')
    op.drop_table('schedule_redistributions')
    op.drop_index(op.f('ix_daily_assignments_uid'), table_name='daily_assignments')
    op.drop_index(op.f('ix_daily_assignments_schedule_id'), table_name='daily_assignments')
    op.drop_index(op.f('ix_daily_assignments_recommendation_id'), table_name='daily_assignments')
    op.drop_index(op.f('ix_daily_assignments_id'), table_name='daily_assignments')
    op.drop_index(op.f('ix_daily_assignments_assignment_date'), table_name='daily_assignments')
    op.drop_index('idx_assignment_user_date', table_name='daily_assignments')
    op.drop_index('idx_assignment_schedule_date', table_name='daily_assignments')
    op.drop_table('daily_assignments')
    op.drop_index(op.f('ix_recommendation_schedules_uid'), table_name='recommendation_schedules')
    op.drop_index(op.f('ix_recommendation_schedules_id'), table_name='recommendation_schedules')
    op.drop_index('idx_schedule_user_active', table_name='recommendation_schedules')
    op.drop_index('idx_schedule_next_fire', table_name='recommendation_schedules')
    op.drop_table('recommendation_schedules')
    # ### end Alembic commands ###
