"""add_scheduling_tables

Revision ID: a39aaace7e05
Revises: 0ac131da102e
Create Date: 2025-08-21 07:53:52.430509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a39aaace7e05'
down_revision: Union[str, None] = '0ac131da102e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. First clean up invalid recommendation_advices data
    op.execute("DELETE FROM recommendation_advices WHERE recommendation_id NOT IN (SELECT id FROM recommendation_records)")
    
    # 2. Create new tables
    op.create_table('recommendation_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=255), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('completion_date', sa.Date(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendation_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uid'], ['user_profiles.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_completion_rec_date', 'recommendation_completions', ['recommendation_id', 'completion_date'], unique=False)
    op.create_index('idx_completion_user_date', 'recommendation_completions', ['uid', 'completion_date'], unique=False)
    op.create_index(op.f('ix_recommendation_completions_completion_date'), 'recommendation_completions', ['completion_date'], unique=False)
    op.create_index(op.f('ix_recommendation_completions_id'), 'recommendation_completions', ['id'], unique=False)
    op.create_index(op.f('ix_recommendation_completions_recommendation_id'), 'recommendation_completions', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_recommendation_completions_uid'), 'recommendation_completions', ['uid'], unique=False)
    op.create_table('user_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('scheduled_recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('completed_recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['user_profiles.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_schedule_date', 'user_schedules', ['uid', 'date'], unique=False)
    op.create_index(op.f('ix_user_schedules_date'), 'user_schedules', ['date'], unique=False)
    op.create_index(op.f('ix_user_schedules_id'), 'user_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_user_schedules_uid'), 'user_schedules', ['uid'], unique=False)
    
    # 3. Modify recommendation_advices table
    op.alter_column('recommendation_advices', 'title',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.drop_index(op.f('ix_recommendation_advices_recommendation_id'), table_name='recommendation_advices')
    op.create_foreign_key(None, 'recommendation_advices', 'recommendation_records', ['recommendation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recommendation_advices', type_='foreignkey')
    op.create_index(op.f('ix_recommendation_advices_recommendation_id'), 'recommendation_advices', ['recommendation_id'], unique=False)
    op.alter_column('recommendation_advices', 'title',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.drop_index(op.f('ix_user_schedules_uid'), table_name='user_schedules')
    op.drop_index(op.f('ix_user_schedules_id'), table_name='user_schedules')
    op.drop_index(op.f('ix_user_schedules_date'), table_name='user_schedules')
    op.drop_index('idx_user_schedule_date', table_name='user_schedules')
    op.drop_table('user_schedules')
    op.drop_index(op.f('ix_recommendation_completions_uid'), table_name='recommendation_completions')
    op.drop_index(op.f('ix_recommendation_completions_recommendation_id'), table_name='recommendation_completions')
    op.drop_index(op.f('ix_recommendation_completions_id'), table_name='recommendation_completions')
    op.drop_index(op.f('ix_recommendation_completions_completion_date'), table_name='recommendation_completions')
    op.drop_index('idx_completion_user_date', table_name='recommendation_completions')
    op.drop_index('idx_completion_rec_date', table_name='recommendation_completions')
    op.drop_table('recommendation_completions')
    # ### end Alembic commands ###
