"""add_lifestyle_focus_to_question_sessions

Revision ID: c5b30e69e462
Revises: 5c6207e75696
Create Date: 2025-12-16 01:42:47.174201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5b30e69e462'
down_revision: Union[str, None] = '5c6207e75696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_chat_feedback_message'), table_name='chat_feedback')
    op.drop_index(op.f('idx_chat_feedback_rating'), table_name='chat_feedback')
    op.drop_index(op.f('idx_chat_feedback_user'), table_name='chat_feedback')
    op.drop_index(op.f('ix_chat_feedback_id'), table_name='chat_feedback')
    op.drop_index(op.f('ix_chat_feedback_message_id'), table_name='chat_feedback')
    op.drop_index(op.f('ix_chat_feedback_uid'), table_name='chat_feedback')
    op.drop_table('chat_feedback')
    op.alter_column('assignment_skip_logs', 'skip_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_index(op.f('ix_skip_logs_recommendation'), table_name='assignment_skip_logs')
    op.drop_index(op.f('ix_skip_logs_user_date'), table_name='assignment_skip_logs')
    op.drop_index(op.f('ix_skip_logs_user_id'), table_name='assignment_skip_logs')
    op.create_index('idx_skip_logs_recommendation', 'assignment_skip_logs', ['recommendation_id'], unique=False)
    op.create_index('idx_skip_logs_user_date', 'assignment_skip_logs', ['user_id', 'skip_date'], unique=False)
    op.create_index(op.f('ix_assignment_skip_logs_user_id'), 'assignment_skip_logs', ['user_id'], unique=False)
    op.create_foreign_key(None, 'assignment_skip_logs', 'recommendation_records', ['recommendation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'assignment_skip_logs', 'daily_assignments', ['assignment_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_chat_messages_session'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_session_created'), table_name='chat_messages')
    op.create_index('idx_chat_messages_session_created', 'chat_messages', ['session_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.drop_index(op.f('ix_chat_sessions_last_msg'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_user_context'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_user_status'), table_name='chat_sessions')
    op.create_index('idx_chat_sessions_last_msg', 'chat_sessions', ['last_message_at'], unique=False)
    op.create_index('idx_chat_sessions_user_status', 'chat_sessions', ['user_id', 'status'], unique=False)
    op.drop_index(op.f('ix_conv_summaries_user_id'), table_name='conversation_summaries')
    op.drop_index(op.f('ix_conv_summaries_user_period'), table_name='conversation_summaries')
    op.create_index('idx_conv_summaries_user_period', 'conversation_summaries', ['user_id', 'summary_type', 'period_start'], unique=True)
    op.create_index(op.f('ix_conversation_summaries_user_id'), 'conversation_summaries', ['user_id'], unique=False)
    op.add_column('question_sessions', sa.Column('lifestyle_focus', sa.ARRAY(sa.String()), nullable=True))
    op.alter_column('symptom_logs', 'logged_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_index(op.f('ix_symptom_logs_user_date'), table_name='symptom_logs')
    op.drop_index(op.f('ix_symptom_logs_user_type_date'), table_name='symptom_logs')
    op.create_index('idx_symptom_logs_user_date', 'symptom_logs', ['user_id', 'logged_date'], unique=False)
    op.create_index('idx_symptom_logs_user_type_date', 'symptom_logs', ['user_id', 'symptom_type', 'logged_date'], unique=False)
    op.add_column('user_profiles', sa.Column('chatbot_memory', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'chatbot_memory')
    op.drop_index('idx_symptom_logs_user_type_date', table_name='symptom_logs')
    op.drop_index('idx_symptom_logs_user_date', table_name='symptom_logs')
    op.create_index(op.f('ix_symptom_logs_user_type_date'), 'symptom_logs', ['user_id', 'symptom_type', 'logged_date'], unique=False)
    op.create_index(op.f('ix_symptom_logs_user_date'), 'symptom_logs', ['user_id', 'logged_date'], unique=False)
    op.alter_column('symptom_logs', 'logged_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('question_sessions', 'lifestyle_focus')
    op.drop_index(op.f('ix_conversation_summaries_user_id'), table_name='conversation_summaries')
    op.drop_index('idx_conv_summaries_user_period', table_name='conversation_summaries')
    op.create_index(op.f('ix_conv_summaries_user_period'), 'conversation_summaries', ['user_id', 'summary_type', 'period_start'], unique=True)
    op.create_index(op.f('ix_conv_summaries_user_id'), 'conversation_summaries', ['user_id'], unique=False)
    op.drop_index('idx_chat_sessions_user_status', table_name='chat_sessions')
    op.drop_index('idx_chat_sessions_last_msg', table_name='chat_sessions')
    op.create_index(op.f('ix_chat_sessions_user_status'), 'chat_sessions', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_context'), 'chat_sessions', ['user_id', 'conversation_context'], unique=False)
    op.create_index(op.f('ix_chat_sessions_last_msg'), 'chat_sessions', ['last_message_at'], unique=False)
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index('idx_chat_messages_session_created', table_name='chat_messages')
    op.create_index(op.f('ix_chat_messages_session_created'), 'chat_messages', ['session_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_session'), 'chat_messages', ['session_id'], unique=False)
    op.drop_constraint(None, 'assignment_skip_logs', type_='foreignkey')
    op.drop_constraint(None, 'assignment_skip_logs', type_='foreignkey')
    op.drop_index(op.f('ix_assignment_skip_logs_user_id'), table_name='assignment_skip_logs')
    op.drop_index('idx_skip_logs_user_date', table_name='assignment_skip_logs')
    op.drop_index('idx_skip_logs_recommendation', table_name='assignment_skip_logs')
    op.create_index(op.f('ix_skip_logs_user_id'), 'assignment_skip_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_skip_logs_user_date'), 'assignment_skip_logs', ['user_id', 'skip_date'], unique=False)
    op.create_index(op.f('ix_skip_logs_recommendation'), 'assignment_skip_logs', ['recommendation_id'], unique=False)
    op.alter_column('assignment_skip_logs', 'skip_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.create_table('chat_feedback',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('uid', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('feedback_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('original_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('original_response', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['user_profiles.uid'], name=op.f('chat_feedback_uid_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_feedback_pkey'))
    )
    op.create_index(op.f('ix_chat_feedback_uid'), 'chat_feedback', ['uid'], unique=False)
    op.create_index(op.f('ix_chat_feedback_message_id'), 'chat_feedback', ['message_id'], unique=False)
    op.create_index(op.f('ix_chat_feedback_id'), 'chat_feedback', ['id'], unique=False)
    op.create_index(op.f('idx_chat_feedback_user'), 'chat_feedback', ['uid'], unique=False)
    op.create_index(op.f('idx_chat_feedback_rating'), 'chat_feedback', ['rating'], unique=False)
    op.create_index(op.f('idx_chat_feedback_message'), 'chat_feedback', ['message_id'], unique=False)
    # ### end Alembic commands ###
