"""create session processing status table

Revision ID: create_session_processing_status
Revises: 04bd3784e1e7
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'create_session_processing_status'
down_revision = '04bd3784e1e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_processing_status',
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('processing_status', sa.String(length=50), nullable=True),
    sa.Column('phase', sa.String(length=100), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('food_status', sa.String(length=50), nullable=True),
    sa.Column('movement_status', sa.String(length=50), nullable=True),
    sa.Column('mindfulness_status', sa.String(length=50), nullable=True),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_session_processing_status_session_id'), 'session_processing_status', ['session_id'], unique=False)
    op.create_index('idx_processing_status', 'session_processing_status', ['processing_status'], unique=False)
    op.create_index('idx_heartbeat_at', 'session_processing_status', ['heartbeat_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_heartbeat_at', table_name='session_processing_status')
    op.drop_index('idx_processing_status', table_name='session_processing_status')
    op.drop_index(op.f('ix_session_processing_status_session_id'), table_name='session_processing_status')
    op.drop_table('session_processing_status')
    # ### end Alembic commands ###
