"""update_recommendation_schedule_to_utc

Revision ID: d580e1d3df52
Revises: 04bd3784e1e7
Create Date: 2025-08-23 03:28:12.968051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd580e1d3df52'
down_revision: Union[str, None] = '04bd3784e1e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First add columns with nullable=True
    op.add_column('recommendation_schedules', sa.Column('start_date_utc', sa.DateTime(), nullable=True))
    op.add_column('recommendation_schedules', sa.Column('end_date_utc', sa.DateTime(), nullable=True))
    
    # Convert existing data to UTC and update
    from sqlalchemy import text
    op.execute(text("""
        UPDATE recommendation_schedules 
        SET start_date_utc = start_date::timestamp,
            end_date_utc = end_date::timestamp
        WHERE start_date IS NOT NULL
    """))
    
    # Change start_date_utc to NOT NULL
    op.alter_column('recommendation_schedules', 'start_date_utc', nullable=False)
    
    op.alter_column('recommendation_schedules', 'recommendation_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.drop_index(op.f('idx_schedule_next_fire'), table_name='recommendation_schedules')
    op.drop_index(op.f('idx_schedule_user_active'), table_name='recommendation_schedules')
    op.create_index(op.f('ix_recommendation_schedules_recommendation_id'), 'recommendation_schedules', ['recommendation_id'], unique=False)
    op.drop_constraint(op.f('recommendation_schedules_uid_fkey'), 'recommendation_schedules', type_='foreignkey')
    op.drop_column('recommendation_schedules', 'last_emitted_local_date')
    op.drop_column('recommendation_schedules', 'tzid')
    op.drop_column('recommendation_schedules', 'is_active')
    op.drop_column('recommendation_schedules', 'start_date')
    op.drop_column('recommendation_schedules', 'end_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendation_schedules', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('recommendation_schedules', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('recommendation_schedules', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('recommendation_schedules', sa.Column('tzid', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('recommendation_schedules', sa.Column('last_emitted_local_date', sa.DATE(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('recommendation_schedules_uid_fkey'), 'recommendation_schedules', 'user_profiles', ['uid'], ['uid'], ondelete='CASCADE')
    op.drop_index(op.f('ix_recommendation_schedules_recommendation_id'), table_name='recommendation_schedules')
    op.create_index(op.f('idx_schedule_user_active'), 'recommendation_schedules', ['uid', 'is_active'], unique=False)
    op.create_index(op.f('idx_schedule_next_fire'), 'recommendation_schedules', ['next_fire_at_utc'], unique=False)
    op.alter_column('recommendation_schedules', 'recommendation_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('recommendation_schedules', 'end_date_utc')
    op.drop_column('recommendation_schedules', 'start_date_utc')
    # ### end Alembic commands ###
