"""Canonical schema baseline for a completely blank PostgreSQL 17 database.

This revision is an immutable snapshot of ``app.core.database.Base.metadata``.
The historical revisions in ``alembic/versions`` are intentionally excluded
from the active revision path; they are retained only as an audit record.

Revision ID: 20260723_0001
Revises: 
Create Date: 2026-07-23 20:10:37.150176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20260723_0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_library',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('prompt_embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('variant_type', sa.String(length=20), nullable=True),
    sa.Column('generation_model', sa.String(length=50), nullable=True),
    sa.Column('generation_cost', sa.String(length=50), nullable=True),
    sa.Column('generation_time_ms', sa.Integer(), nullable=True),
    sa.Column('image_width', sa.Integer(), nullable=True),
    sa.Column('image_height', sa.Integer(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('used_by_users', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_image_library_category', 'image_library', ['category', 'variant_type'], unique=False)
    op.create_index('idx_image_library_usage', 'image_library', ['usage_count'], unique=False)
    op.create_index(op.f('ix_image_library_id'), 'image_library', ['id'], unique=False)
    op.create_table('pubmed_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sa.String(length=32), nullable=False),
    sa.Column('query_normalized', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('hormone', sa.String(length=50), nullable=True),
    sa.Column('pubmed_id', sa.String(length=20), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('journal', sa.String(length=255), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('participants', sa.String(length=100), nullable=True),
    sa.Column('finding', sa.Text(), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pubmed_cache_access', 'pubmed_cache', ['access_count'], unique=False)
    op.create_index('idx_pubmed_cache_key', 'pubmed_cache', ['cache_key'], unique=False)
    op.create_index(op.f('ix_pubmed_cache_cache_key'), 'pubmed_cache', ['cache_key'], unique=True)
    op.create_index(op.f('ix_pubmed_cache_id'), 'pubmed_cache', ['id'], unique=False)
    op.create_table('question_sessions',
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('period_description', sa.String(length=100), nullable=True),
    sa.Column('birth_control', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('last_period_date_utc', sa.DateTime(), nullable=True),
    sa.Column('cycle_length', sa.String(length=50), nullable=True),
    sa.Column('period_concerns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('body_concerns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('skin_hair_concerns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mental_health_concerns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('other_concerns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('top_concern', sa.String(length=255), nullable=True),
    sa.Column('diagnosed_conditions', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('family_history', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('workout_intensity', sa.String(length=50), nullable=True),
    sa.Column('sleep_duration', sa.String(length=50), nullable=True),
    sa.Column('stress_level', sa.String(length=50), nullable=True),
    sa.Column('survey_timezone', sa.String(length=50), nullable=True),
    sa.Column('lifestyle_focus', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('primary_hormone', sa.String(length=50), nullable=True),
    sa.Column('secondary_hormones', sa.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_question_sessions_session_id'), 'question_sessions', ['session_id'], unique=False)
    op.create_table('recommendation_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=255), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('recommendation_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('purpose', sa.String(length=500), nullable=True),
    sa.Column('specific_action', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('contraindications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('conditions', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('symptoms', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('hormones', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('food_amounts', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('food_items', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('exercise_durations', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('exercise_types', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('exercise_intensities', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('mindfulness_durations', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('mindfulness_techniques', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('frequency_detail', sa.String(length=100), nullable=True),
    sa.Column('duration_weeks', sa.Integer(), nullable=True),
    sa.Column('optimal_times', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('research_summary', sa.Text(), nullable=True),
    sa.Column('research_studies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_profile_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_records_id'), 'recommendation_records', ['id'], unique=False)
    op.create_index(op.f('ix_recommendation_records_session_id'), 'recommendation_records', ['session_id'], unique=False)
    op.create_index(op.f('ix_recommendation_records_uid'), 'recommendation_records', ['uid'], unique=False)
    op.create_table('session_processing_status',
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('processing_status', sa.String(length=50), nullable=True),
    sa.Column('phase', sa.String(length=100), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('food_status', sa.String(length=50), nullable=True),
    sa.Column('movement_status', sa.String(length=50), nullable=True),
    sa.Column('mindfulness_status', sa.String(length=50), nullable=True),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index('idx_heartbeat_at', 'session_processing_status', ['heartbeat_at'], unique=False)
    op.create_index('idx_processing_status', 'session_processing_status', ['processing_status'], unique=False)
    op.create_index(op.f('ix_session_processing_status_session_id'), 'session_processing_status', ['session_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('uid', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('current_timezone', sa.String(length=50), nullable=True),
    sa.Column('lifestyle_focus', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('chatbot_memory', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('feedback_summary', sa.Text(), nullable=True),
    sa.Column('feedback_summary_updated_at', sa.DateTime(), nullable=True),
    sa.Column('feedback_last_count', sa.Integer(), nullable=False),
    sa.Column('weekly_checkin_due_date', sa.Date(), nullable=True),
    sa.Column('last_weekly_checkin_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_user_profiles_uid'), 'user_profiles', ['uid'], unique=False)
    op.create_table('user_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=255), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('period_description', sa.String(length=100), nullable=True),
    sa.Column('birth_control', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('last_period_date_utc', sa.DateTime(), nullable=True),
    sa.Column('cycle_length', sa.String(length=50), nullable=True),
    sa.Column('period_concerns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('body_concerns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('skin_hair_concerns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mental_health_concerns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('other_concerns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('top_concern', sa.String(length=255), nullable=True),
    sa.Column('diagnosed_conditions', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('family_history', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('workout_intensity', sa.String(length=50), nullable=True),
    sa.Column('sleep_duration', sa.String(length=50), nullable=True),
    sa.Column('stress_level', sa.String(length=50), nullable=True),
    sa.Column('survey_timezone', sa.String(length=50), nullable=True),
    sa.Column('primary_hormone', sa.String(length=50), nullable=True),
    sa.Column('secondary_hormones', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('lifestyle_focus', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_responses_id'), 'user_responses', ['id'], unique=False)
    op.create_index(op.f('ix_user_responses_uid'), 'user_responses', ['uid'], unique=False)
    op.create_table('weekly_checkin_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_key', sa.String(length=50), nullable=False),
    sa.Column('question_type', sa.String(length=30), nullable=False),
    sa.Column('question_template', sa.Text(), nullable=False),
    sa.Column('default_tap_options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('concern_type', sa.String(length=50), nullable=True),
    sa.Column('question_order', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('show_condition', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_key')
    )
    op.create_index('idx_question_concern', 'weekly_checkin_questions', ['concern_type', 'is_active'], unique=False)
    op.create_index('idx_question_order', 'weekly_checkin_questions', ['question_order', 'is_active'], unique=False)
    op.create_index(op.f('ix_weekly_checkin_questions_id'), 'weekly_checkin_questions', ['id'], unique=False)
    op.create_table('action_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=255), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('plan_date', sa.Date(), nullable=False),
    sa.Column('primary_hormone', sa.String(length=50), nullable=True),
    sa.Column('secondary_hormones', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('cycle_day', sa.Integer(), nullable=True),
    sa.Column('cycle_phase', sa.String(length=50), nullable=True),
    sa.Column('lifestyle_focus', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('generation_cost', sa.String(length=50), nullable=True),
    sa.Column('generation_time_ms', sa.Integer(), nullable=True),
    sa.Column('gpt_model_used', sa.String(length=50), nullable=True),
    sa.Column('is_regenerated', sa.Boolean(), nullable=True),
    sa.Column('feedback_collected', sa.Boolean(), nullable=True),
    sa.Column('review_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['user_profiles.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_action_plan_session_date', 'action_plans', ['session_id', 'plan_date'], unique=False)
    op.create_index('idx_action_plan_user_date', 'action_plans', ['uid', 'plan_date'], unique=False)
    op.create_index(op.f('ix_action_plans_id'), 'action_plans', ['id'], unique=False)
    op.create_index(op.f('ix_action_plans_plan_date'), 'action_plans', ['plan_date'], unique=False)
    op.create_index(op.f('ix_action_plans_session_id'), 'action_plans', ['session_id'], unique=False)
    op.create_index(op.f('ix_action_plans_uid'), 'action_plans', ['uid'], unique=False)
    op.create_index('uq_action_plan_session_date', 'action_plans', ['session_id', 'plan_date'], unique=True, postgresql_where=sa.text('session_id IS NOT NULL'))
    op.create_index('uq_action_plan_user_date', 'action_plans', ['uid', 'plan_date'], unique=True, postgresql_where=sa.text('uid IS NOT NULL'))
    op.create_table('care_plan_checkin_threads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('uid', sa.String(length=255), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('raw_messages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rolling_summary', sa.Text(), nullable=True),
    sa.Column('summarized_message_count', sa.Integer(), nullable=True),
    sa.Column('last_summarized_at', sa.DateTime(), nullable=True),
    sa.Column('actionable_insights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['user_profiles.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_care_plan_thread_user_closed', 'care_plan_checkin_threads', ['uid', 'is_closed'], unique=False)
    op.create_index('idx_care_plan_thread_user_date', 'care_plan_checkin_threads', ['uid', 'local_date'], unique=False)
    op.create_index(op.f('ix_care_plan_checkin_threads_local_date'), 'care_plan_checkin_threads', ['local_date'], unique=False)
    op.create_index(op.f('ix_care_plan_checkin_threads_uid'), 'care_plan_checkin_threads', ['uid'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('conversation_context', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('current_step', sa.String(length=100), nullable=True),
    sa.Column('current_flow_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chat_sessions_last_msg', 'chat_sessions', ['last_message_at'], unique=False)
    op.create_index('idx_chat_sessions_user_status', 'chat_sessions', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('conversation_summaries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('summary_type', sa.String(length=20), nullable=False),
    sa.Column('summary_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conv_summaries_user_period', 'conversation_summaries', ['user_id', 'summary_type', 'period_start'], unique=True)
    op.create_index(op.f('ix_conversation_summaries_user_id'), 'conversation_summaries', ['user_id'], unique=False)
    op.create_table('mood_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('mood_level', sa.Integer(), nullable=False),
    sa.Column('energy_level', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.Column('logged_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mood_logs_user_date_unique', 'mood_logs', ['user_id', 'logged_date'], unique=True)
    op.create_index('idx_mood_logs_user_logged_at', 'mood_logs', ['user_id', 'logged_at'], unique=False)
    op.create_index(op.f('ix_mood_logs_logged_date'), 'mood_logs', ['logged_date'], unique=False)
    op.create_index(op.f('ix_mood_logs_user_id'), 'mood_logs', ['user_id'], unique=False)
    op.create_table('recommendation_advices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=255), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('advice_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('recommendation_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendation_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_advices_id'), 'recommendation_advices', ['id'], unique=False)
    op.create_index(op.f('ix_recommendation_advices_session_id'), 'recommendation_advices', ['session_id'], unique=False)
    op.create_index(op.f('ix_recommendation_advices_uid'), 'recommendation_advices', ['uid'], unique=False)
    op.create_table('recommendation_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=255), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('completion_date', sa.Date(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendation_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uid'], ['user_profiles.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_completion_rec_date', 'recommendation_completions', ['recommendation_id', 'completion_date'], unique=False)
    op.create_index('idx_completion_user_date', 'recommendation_completions', ['uid', 'completion_date'], unique=False)
    op.create_index(op.f('ix_recommendation_completions_completion_date'), 'recommendation_completions', ['completion_date'], unique=False)
    op.create_index(op.f('ix_recommendation_completions_id'), 'recommendation_completions', ['id'], unique=False)
    op.create_index(op.f('ix_recommendation_completions_recommendation_id'), 'recommendation_completions', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_recommendation_completions_uid'), 'recommendation_completions', ['uid'], unique=False)
    op.create_table('recommendation_redistributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=255), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('original_date', sa.Date(), nullable=False),
    sa.Column('redistributed_dates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('redistribution_reason', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendation_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uid'], ['user_profiles.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_redistribution_date', 'recommendation_redistributions', ['original_date'], unique=False)
    op.create_index('idx_redistribution_user_rec', 'recommendation_redistributions', ['uid', 'recommendation_id'], unique=False)
    op.create_index(op.f('ix_recommendation_redistributions_id'), 'recommendation_redistributions', ['id'], unique=False)
    op.create_index(op.f('ix_recommendation_redistributions_original_date'), 'recommendation_redistributions', ['original_date'], unique=False)
    op.create_index(op.f('ix_recommendation_redistributions_recommendation_id'), 'recommendation_redistributions', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_recommendation_redistributions_uid'), 'recommendation_redistributions', ['uid'], unique=False)
    op.create_table('recommendation_schedules',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uid', sa.String(length=255), nullable=False),
    sa.Column('recommendation_id', sa.BigInteger(), nullable=False),
    sa.Column('start_date_utc', sa.DateTime(), nullable=False),
    sa.Column('end_date_utc', sa.DateTime(), nullable=True),
    sa.Column('next_fire_at_utc', sa.DateTime(), nullable=True),
    sa.Column('rrule', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendation_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_schedules_id'), 'recommendation_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_recommendation_schedules_recommendation_id'), 'recommendation_schedules', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_recommendation_schedules_uid'), 'recommendation_schedules', ['uid'], unique=False)
    op.create_table('symptom_checkin_threads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('uid', sa.String(length=255), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('raw_messages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rolling_summary', sa.Text(), nullable=True),
    sa.Column('summarized_message_count', sa.Integer(), nullable=True),
    sa.Column('last_summarized_at', sa.DateTime(), nullable=True),
    sa.Column('actionable_insights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['user_profiles.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_symptom_thread_user_closed', 'symptom_checkin_threads', ['uid', 'is_closed'], unique=False)
    op.create_index('idx_symptom_thread_user_date', 'symptom_checkin_threads', ['uid', 'local_date'], unique=False)
    op.create_index(op.f('ix_symptom_checkin_threads_local_date'), 'symptom_checkin_threads', ['local_date'], unique=False)
    op.create_index(op.f('ix_symptom_checkin_threads_uid'), 'symptom_checkin_threads', ['uid'], unique=False)
    op.create_table('user_rewards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=255), nullable=False),
    sa.Column('reward_id', sa.String(length=50), nullable=False),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['user_profiles.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_reward_uid', 'user_rewards', ['uid'], unique=False)
    op.create_index(op.f('ix_user_rewards_id'), 'user_rewards', ['id'], unique=False)
    op.create_index(op.f('ix_user_rewards_uid'), 'user_rewards', ['uid'], unique=False)
    op.create_table('user_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('scheduled_recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('completed_recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['user_profiles.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_schedule_date', 'user_schedules', ['uid', 'date'], unique=False)
    op.create_index(op.f('ix_user_schedules_date'), 'user_schedules', ['date'], unique=False)
    op.create_index(op.f('ix_user_schedules_id'), 'user_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_user_schedules_uid'), 'user_schedules', ['uid'], unique=False)
    op.create_table('user_streak_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=255), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=True),
    sa.Column('longest_streak', sa.Integer(), nullable=True),
    sa.Column('last_activity_date', sa.Date(), nullable=True),
    sa.Column('freeze_count', sa.Integer(), nullable=True),
    sa.Column('freeze_used_date', sa.Date(), nullable=True),
    sa.Column('freeze_used_dates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('daily_refresh_count', sa.Integer(), nullable=True),
    sa.Column('last_refresh_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['user_profiles.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    op.create_index('idx_streak_uid', 'user_streak_data', ['uid'], unique=False)
    op.create_index(op.f('ix_user_streak_data_id'), 'user_streak_data', ['id'], unique=False)
    op.create_table('weekly_checkin_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('uid', sa.String(length=255), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('questions_asked', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('question_count', sa.Integer(), nullable=True),
    sa.Column('topics_covered', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('weekly_summary', sa.Text(), nullable=True),
    sa.Column('insights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('personalization_updates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cycle_day', sa.Integer(), nullable=True),
    sa.Column('cycle_phase', sa.String(length=50), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['user_profiles.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_weekly_session_complete', 'weekly_checkin_sessions', ['uid', 'is_complete'], unique=False)
    op.create_index('idx_weekly_session_user_date', 'weekly_checkin_sessions', ['uid', 'session_date'], unique=False)
    op.create_index(op.f('ix_weekly_checkin_sessions_session_date'), 'weekly_checkin_sessions', ['session_date'], unique=False)
    op.create_index(op.f('ix_weekly_checkin_sessions_uid'), 'weekly_checkin_sessions', ['uid'], unique=False)
    op.create_table('weekly_checkins',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('uid', sa.String(length=255), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('check_in_date', sa.Date(), nullable=False),
    sa.Column('top_concern', sa.String(length=100), nullable=True),
    sa.Column('concern_severity', sa.Integer(), nullable=True),
    sa.Column('overall_wellbeing', sa.Integer(), nullable=True),
    sa.Column('factors_positive', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('factors_negative', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('action_reflections', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('concerns_next_week', sa.Text(), nullable=True),
    sa.Column('cycle_day_at_checkin', sa.Integer(), nullable=True),
    sa.Column('phase_at_checkin', sa.String(length=30), nullable=True),
    sa.Column('conversation_summary', sa.Text(), nullable=True),
    sa.Column('raw_messages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actionable_insights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.Column('current_question_index', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['user_profiles.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_checkin_complete', 'weekly_checkins', ['uid', 'is_complete'], unique=False)
    op.create_index('idx_checkin_user_date', 'weekly_checkins', ['uid', 'check_in_date'], unique=False)
    op.create_index('idx_checkin_user_week', 'weekly_checkins', ['uid', 'year', 'week_number'], unique=True)
    op.create_index(op.f('ix_weekly_checkins_uid'), 'weekly_checkins', ['uid'], unique=False)
    op.create_table('action_plan_daily_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=255), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=False),
    sa.Column('review_completed_at', sa.DateTime(), nullable=True),
    sa.Column('items_review_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('streak_action', sa.String(length=20), nullable=True),
    sa.Column('freezes_used_count', sa.Integer(), nullable=True),
    sa.Column('items_carried_forward', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('items_marked_complete', sa.Integer(), nullable=True),
    sa.Column('items_replaced', sa.Integer(), nullable=True),
    sa.Column('items_skipped', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['action_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uid'], ['user_profiles.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_daily_review_plan', 'action_plan_daily_reviews', ['plan_id'], unique=False)
    op.create_index('idx_daily_review_user_date', 'action_plan_daily_reviews', ['uid', 'review_date'], unique=False)
    op.create_index(op.f('ix_action_plan_daily_reviews_id'), 'action_plan_daily_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_action_plan_daily_reviews_plan_id'), 'action_plan_daily_reviews', ['plan_id'], unique=False)
    op.create_index(op.f('ix_action_plan_daily_reviews_review_date'), 'action_plan_daily_reviews', ['review_date'], unique=False)
    op.create_index(op.f('ix_action_plan_daily_reviews_uid'), 'action_plan_daily_reviews', ['uid'], unique=False)
    op.create_table('action_plan_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=255), nullable=False),
    sa.Column('structure_valid', sa.Boolean(), nullable=False),
    sa.Column('personalization_score', sa.Integer(), nullable=True),
    sa.Column('condition_appropriateness', sa.Integer(), nullable=True),
    sa.Column('feedback_alignment_score', sa.Integer(), nullable=True),
    sa.Column('preference_compliance_score', sa.Integer(), nullable=True),
    sa.Column('citation_validity_score', sa.Integer(), nullable=True),
    sa.Column('citation_relevance_score', sa.Integer(), nullable=True),
    sa.Column('overall_quality_score', sa.Integer(), nullable=True),
    sa.Column('evaluation_cost', sa.String(length=50), nullable=True),
    sa.Column('evaluation_time_ms', sa.Integer(), nullable=True),
    sa.Column('evaluator_model', sa.String(length=50), nullable=True),
    sa.Column('llm_evaluation_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['action_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id')
    )
    op.create_index('idx_evaluation_plan', 'action_plan_evaluations', ['plan_id'], unique=False)
    op.create_index('idx_evaluation_score', 'action_plan_evaluations', ['overall_quality_score'], unique=False)
    op.create_index('idx_evaluation_user', 'action_plan_evaluations', ['uid', 'created_at'], unique=False)
    op.create_index(op.f('ix_action_plan_evaluations_id'), 'action_plan_evaluations', ['id'], unique=False)
    op.create_index(op.f('ix_action_plan_evaluations_uid'), 'action_plan_evaluations', ['uid'], unique=False)
    op.create_table('action_plan_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=255), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('time_slot', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('specific_action', sa.Text(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('target_hormone', sa.String(length=50), nullable=False),
    sa.Column('hormone_persona_intro', sa.Text(), nullable=True),
    sa.Column('food_amounts', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('food_items', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('exercise_durations', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('exercise_types', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('exercise_intensities', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('mindfulness_durations', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('mindfulness_techniques', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('conditions', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('symptoms', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('hero_image_url', sa.Text(), nullable=True),
    sa.Column('hero_image_prompt', sa.Text(), nullable=True),
    sa.Column('research_studies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('is_replaced', sa.Boolean(), nullable=True),
    sa.Column('replaced_at', sa.DateTime(), nullable=True),
    sa.Column('replacement_reason', sa.Text(), nullable=True),
    sa.Column('carried_forward_from', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['action_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_action_item_plan', 'action_plan_items', ['plan_id'], unique=False)
    op.create_index('idx_action_item_user_date', 'action_plan_items', ['uid', 'created_at'], unique=False)
    op.create_index(op.f('ix_action_plan_items_id'), 'action_plan_items', ['id'], unique=False)
    op.create_index(op.f('ix_action_plan_items_plan_id'), 'action_plan_items', ['plan_id'], unique=False)
    op.create_index(op.f('ix_action_plan_items_session_id'), 'action_plan_items', ['session_id'], unique=False)
    op.create_index(op.f('ix_action_plan_items_uid'), 'action_plan_items', ['uid'], unique=False)
    op.create_table('action_plan_refresh_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=255), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('refresh_date', sa.Date(), nullable=False),
    sa.Column('refresh_count', sa.Integer(), nullable=True),
    sa.Column('original_action', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('replacement_action', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('replacement_reason', sa.String(length=50), nullable=True),
    sa.Column('thread_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['action_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uid'], ['user_profiles.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_refresh_user_date', 'action_plan_refresh_logs', ['uid', 'refresh_date'], unique=False)
    op.create_index(op.f('ix_action_plan_refresh_logs_id'), 'action_plan_refresh_logs', ['id'], unique=False)
    op.create_index(op.f('ix_action_plan_refresh_logs_refresh_date'), 'action_plan_refresh_logs', ['refresh_date'], unique=False)
    op.create_index(op.f('ix_action_plan_refresh_logs_uid'), 'action_plan_refresh_logs', ['uid'], unique=False)
    op.create_table('ai_model_usage_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('primary_model', sa.String(length=100), nullable=False),
    sa.Column('fallback_model', sa.String(length=100), nullable=True),
    sa.Column('switch_reason', sa.Text(), nullable=True),
    sa.Column('final_model_used', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['action_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_model_usage_logs_id'), 'ai_model_usage_logs', ['id'], unique=False)
    op.create_index(op.f('ix_ai_model_usage_logs_user_id'), 'ai_model_usage_logs', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('input_mode', sa.String(length=10), nullable=True),
    sa.Column('selected_choice', sa.String(length=255), nullable=True),
    sa.Column('slider_value', sa.Integer(), nullable=True),
    sa.Column('response_type', sa.String(length=20), nullable=True),
    sa.Column('choices', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('slider_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tools_called', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('retrieval_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('transcription_confidence', sa.Integer(), nullable=True),
    sa.Column('model_used', sa.String(length=50), nullable=True),
    sa.Column('tokens_input', sa.Integer(), nullable=True),
    sa.Column('tokens_output', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('evaluation_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('message_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chat_messages_session_created', 'chat_messages', ['session_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('daily_assignments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uid', sa.String(length=255), nullable=False),
    sa.Column('schedule_id', sa.BigInteger(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('assignment_date', sa.Date(), nullable=False),
    sa.Column('time_group', sa.String(length=50), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendation_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['recommendation_schedules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uid'], ['user_profiles.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assignment_schedule_date', 'daily_assignments', ['schedule_id', 'assignment_date'], unique=False)
    op.create_index('idx_assignment_user_date', 'daily_assignments', ['uid', 'assignment_date'], unique=False)
    op.create_index(op.f('ix_daily_assignments_assignment_date'), 'daily_assignments', ['assignment_date'], unique=False)
    op.create_index(op.f('ix_daily_assignments_id'), 'daily_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_daily_assignments_recommendation_id'), 'daily_assignments', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_daily_assignments_schedule_id'), 'daily_assignments', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_daily_assignments_uid'), 'daily_assignments', ['uid'], unique=False)
    op.create_table('schedule_redistributions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('schedule_id', sa.BigInteger(), nullable=False),
    sa.Column('original_date', sa.Date(), nullable=False),
    sa.Column('override_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['recommendation_schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_redistribution_dates', 'schedule_redistributions', ['original_date', 'override_date'], unique=False)
    op.create_index('idx_redistribution_schedule', 'schedule_redistributions', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_schedule_redistributions_id'), 'schedule_redistributions', ['id'], unique=False)
    op.create_index(op.f('ix_schedule_redistributions_schedule_id'), 'schedule_redistributions', ['schedule_id'], unique=False)
    op.create_table('action_plan_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=255), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('feedback_type', sa.String(length=20), nullable=False),
    sa.Column('action_title', sa.String(length=255), nullable=True),
    sa.Column('action_category', sa.String(length=20), nullable=True),
    sa.Column('target_hormone', sa.String(length=50), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('replacement_reason', sa.Text(), nullable=True),
    sa.Column('replacement_category', sa.String(length=50), nullable=True),
    sa.Column('was_replaced', sa.Boolean(), nullable=True),
    sa.Column('feedback_source', sa.String(length=20), nullable=True),
    sa.Column('cycle_day', sa.Integer(), nullable=True),
    sa.Column('cycle_phase', sa.String(length=50), nullable=True),
    sa.Column('action_shown_at', sa.DateTime(), nullable=True),
    sa.Column('feedback_given_at', sa.DateTime(), nullable=True),
    sa.Column('time_to_feedback_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['action_plan_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['action_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uid'], ['user_profiles.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_feedback_source', 'action_plan_feedback', ['feedback_source'], unique=False)
    op.create_index('idx_feedback_type', 'action_plan_feedback', ['feedback_type'], unique=False)
    op.create_index('idx_feedback_user', 'action_plan_feedback', ['uid', 'created_at'], unique=False)
    op.create_index(op.f('ix_action_plan_feedback_id'), 'action_plan_feedback', ['id'], unique=False)
    op.create_index(op.f('ix_action_plan_feedback_uid'), 'action_plan_feedback', ['uid'], unique=False)
    op.create_table('action_plan_item_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('variant_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('image_prompt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['action_plan_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_plan_item_variants_id'), 'action_plan_item_variants', ['id'], unique=False)
    op.create_index(op.f('ix_action_plan_item_variants_item_id'), 'action_plan_item_variants', ['item_id'], unique=False)
    op.create_table('assignment_skip_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('assignment_id', sa.BigInteger(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('skip_reason', sa.String(length=100), nullable=True),
    sa.Column('reason_notes', sa.Text(), nullable=True),
    sa.Column('alternative_offered', sa.Boolean(), nullable=True),
    sa.Column('alternative_taken_id', sa.Integer(), nullable=True),
    sa.Column('cycle_day', sa.Integer(), nullable=True),
    sa.Column('phase', sa.String(length=30), nullable=True),
    sa.Column('chat_session_id', sa.String(length=36), nullable=True),
    sa.Column('skipped_at', sa.DateTime(), nullable=True),
    sa.Column('skip_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['daily_assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendation_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_skip_logs_recommendation', 'assignment_skip_logs', ['recommendation_id'], unique=False)
    op.create_index('idx_skip_logs_user_date', 'assignment_skip_logs', ['user_id', 'skip_date'], unique=False)
    op.create_index(op.f('ix_assignment_skip_logs_user_id'), 'assignment_skip_logs', ['user_id'], unique=False)
    op.create_table('symptom_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('symptom_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cycle_day', sa.Integer(), nullable=True),
    sa.Column('phase', sa.String(length=30), nullable=True),
    sa.Column('logged_via', sa.String(length=30), nullable=True),
    sa.Column('chat_message_id', sa.String(length=36), nullable=True),
    sa.Column('weekly_checkin_id', sa.String(length=36), nullable=True),
    sa.Column('logged_at', sa.DateTime(), nullable=True),
    sa.Column('logged_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['chat_message_id'], ['chat_messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['weekly_checkin_id'], ['weekly_checkins.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_symptom_logs_checkin', 'symptom_logs', ['weekly_checkin_id'], unique=False)
    op.create_index('idx_symptom_logs_user_date', 'symptom_logs', ['user_id', 'logged_date'], unique=False)
    op.create_index('idx_symptom_logs_user_type_date', 'symptom_logs', ['user_id', 'symptom_type', 'logged_date'], unique=False)
    op.create_index(op.f('ix_symptom_logs_user_id'), 'symptom_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_symptom_logs_weekly_checkin_id'), 'symptom_logs', ['weekly_checkin_id'], unique=False)

    # Reference data required by the resumable weekly check-in flow.  These
    # rows represent the final state after the historical seed/reorder
    # migrations, rather than replaying those state-dependent revisions.
    op.execute(
        sa.text(
            """
            INSERT INTO weekly_checkin_questions (
                question_key,
                question_type,
                question_template,
                default_tap_options,
                question_order,
                is_required,
                is_active
            )
            VALUES
                ('greeting', 'free_text',
                 'Hey! Time for your weekly check-in 💜 How are you feeling this week?',
                 '[]'::jsonb, 1, false, false),
                ('top_concern', 'tap_choice',
                 'What has been bothering you the most this week?',
                 '["Acne", "Bloating", "Mood swings", "Fatigue", "Cramps", "Headaches", "Other"]'::jsonb,
                 2, true, false),
                ('concern_severity', 'slider',
                 'How was your {top_concern} this week?',
                 '[]'::jsonb, 1, true, true),
                ('factors_negative', 'multi_select',
                 'Did any of these make it worse?',
                 '["Ate out more", "Less sleep", "More stress", "Missed workouts", "Sugary foods", "Skipped supplements"]'::jsonb,
                 2, true, true),
                ('factors_positive', 'multi_select',
                 'What helped you feel better?',
                 '["Regular meals", "Good sleep", "Exercise", "Less stress", "Healthy eating", "Supplements"]'::jsonb,
                 3, true, true),
                ('action_reflection', 'tap_choice',
                 'How did you find this week''s action plan?',
                 '["Really helpful", "Somewhat helpful", "Neutral", "Didn''t follow it", "Too difficult"]'::jsonb,
                 4, true, true),
                ('overall_wellbeing', 'slider',
                 'Overall, how would you rate your wellbeing this week? (1=worst, 9=best)',
                 '[]'::jsonb, 5, true, true),
                ('concerns_next_week', 'free_text',
                 'Anything you''re worried about for next week?',
                 '[]'::jsonb, 6, false, true),
                ('closing', 'free_text',
                 'Thanks for checking in! I''ll use this to personalize your action plan. 💜',
                 '[]'::jsonb, 7, false, true)
            """
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_symptom_logs_weekly_checkin_id'), table_name='symptom_logs')
    op.drop_index(op.f('ix_symptom_logs_user_id'), table_name='symptom_logs')
    op.drop_index('idx_symptom_logs_user_type_date', table_name='symptom_logs')
    op.drop_index('idx_symptom_logs_user_date', table_name='symptom_logs')
    op.drop_index('idx_symptom_logs_checkin', table_name='symptom_logs')
    op.drop_table('symptom_logs')
    op.drop_index(op.f('ix_assignment_skip_logs_user_id'), table_name='assignment_skip_logs')
    op.drop_index('idx_skip_logs_user_date', table_name='assignment_skip_logs')
    op.drop_index('idx_skip_logs_recommendation', table_name='assignment_skip_logs')
    op.drop_table('assignment_skip_logs')
    op.drop_index(op.f('ix_action_plan_item_variants_item_id'), table_name='action_plan_item_variants')
    op.drop_index(op.f('ix_action_plan_item_variants_id'), table_name='action_plan_item_variants')
    op.drop_table('action_plan_item_variants')
    op.drop_index(op.f('ix_action_plan_feedback_uid'), table_name='action_plan_feedback')
    op.drop_index(op.f('ix_action_plan_feedback_id'), table_name='action_plan_feedback')
    op.drop_index('idx_feedback_user', table_name='action_plan_feedback')
    op.drop_index('idx_feedback_type', table_name='action_plan_feedback')
    op.drop_index('idx_feedback_source', table_name='action_plan_feedback')
    op.drop_table('action_plan_feedback')
    op.drop_index(op.f('ix_schedule_redistributions_schedule_id'), table_name='schedule_redistributions')
    op.drop_index(op.f('ix_schedule_redistributions_id'), table_name='schedule_redistributions')
    op.drop_index('idx_redistribution_schedule', table_name='schedule_redistributions')
    op.drop_index('idx_redistribution_dates', table_name='schedule_redistributions')
    op.drop_table('schedule_redistributions')
    op.drop_index(op.f('ix_daily_assignments_uid'), table_name='daily_assignments')
    op.drop_index(op.f('ix_daily_assignments_schedule_id'), table_name='daily_assignments')
    op.drop_index(op.f('ix_daily_assignments_recommendation_id'), table_name='daily_assignments')
    op.drop_index(op.f('ix_daily_assignments_id'), table_name='daily_assignments')
    op.drop_index(op.f('ix_daily_assignments_assignment_date'), table_name='daily_assignments')
    op.drop_index('idx_assignment_user_date', table_name='daily_assignments')
    op.drop_index('idx_assignment_schedule_date', table_name='daily_assignments')
    op.drop_table('daily_assignments')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index('idx_chat_messages_session_created', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_ai_model_usage_logs_user_id'), table_name='ai_model_usage_logs')
    op.drop_index(op.f('ix_ai_model_usage_logs_id'), table_name='ai_model_usage_logs')
    op.drop_table('ai_model_usage_logs')
    op.drop_index(op.f('ix_action_plan_refresh_logs_uid'), table_name='action_plan_refresh_logs')
    op.drop_index(op.f('ix_action_plan_refresh_logs_refresh_date'), table_name='action_plan_refresh_logs')
    op.drop_index(op.f('ix_action_plan_refresh_logs_id'), table_name='action_plan_refresh_logs')
    op.drop_index('idx_refresh_user_date', table_name='action_plan_refresh_logs')
    op.drop_table('action_plan_refresh_logs')
    op.drop_index(op.f('ix_action_plan_items_uid'), table_name='action_plan_items')
    op.drop_index(op.f('ix_action_plan_items_session_id'), table_name='action_plan_items')
    op.drop_index(op.f('ix_action_plan_items_plan_id'), table_name='action_plan_items')
    op.drop_index(op.f('ix_action_plan_items_id'), table_name='action_plan_items')
    op.drop_index('idx_action_item_user_date', table_name='action_plan_items')
    op.drop_index('idx_action_item_plan', table_name='action_plan_items')
    op.drop_table('action_plan_items')
    op.drop_index(op.f('ix_action_plan_evaluations_uid'), table_name='action_plan_evaluations')
    op.drop_index(op.f('ix_action_plan_evaluations_id'), table_name='action_plan_evaluations')
    op.drop_index('idx_evaluation_user', table_name='action_plan_evaluations')
    op.drop_index('idx_evaluation_score', table_name='action_plan_evaluations')
    op.drop_index('idx_evaluation_plan', table_name='action_plan_evaluations')
    op.drop_table('action_plan_evaluations')
    op.drop_index(op.f('ix_action_plan_daily_reviews_uid'), table_name='action_plan_daily_reviews')
    op.drop_index(op.f('ix_action_plan_daily_reviews_review_date'), table_name='action_plan_daily_reviews')
    op.drop_index(op.f('ix_action_plan_daily_reviews_plan_id'), table_name='action_plan_daily_reviews')
    op.drop_index(op.f('ix_action_plan_daily_reviews_id'), table_name='action_plan_daily_reviews')
    op.drop_index('idx_daily_review_user_date', table_name='action_plan_daily_reviews')
    op.drop_index('idx_daily_review_plan', table_name='action_plan_daily_reviews')
    op.drop_table('action_plan_daily_reviews')
    op.drop_index(op.f('ix_weekly_checkins_uid'), table_name='weekly_checkins')
    op.drop_index('idx_checkin_user_week', table_name='weekly_checkins')
    op.drop_index('idx_checkin_user_date', table_name='weekly_checkins')
    op.drop_index('idx_checkin_complete', table_name='weekly_checkins')
    op.drop_table('weekly_checkins')
    op.drop_index(op.f('ix_weekly_checkin_sessions_uid'), table_name='weekly_checkin_sessions')
    op.drop_index(op.f('ix_weekly_checkin_sessions_session_date'), table_name='weekly_checkin_sessions')
    op.drop_index('idx_weekly_session_user_date', table_name='weekly_checkin_sessions')
    op.drop_index('idx_weekly_session_complete', table_name='weekly_checkin_sessions')
    op.drop_table('weekly_checkin_sessions')
    op.drop_index(op.f('ix_user_streak_data_id'), table_name='user_streak_data')
    op.drop_index('idx_streak_uid', table_name='user_streak_data')
    op.drop_table('user_streak_data')
    op.drop_index(op.f('ix_user_schedules_uid'), table_name='user_schedules')
    op.drop_index(op.f('ix_user_schedules_id'), table_name='user_schedules')
    op.drop_index(op.f('ix_user_schedules_date'), table_name='user_schedules')
    op.drop_index('idx_user_schedule_date', table_name='user_schedules')
    op.drop_table('user_schedules')
    op.drop_index(op.f('ix_user_rewards_uid'), table_name='user_rewards')
    op.drop_index(op.f('ix_user_rewards_id'), table_name='user_rewards')
    op.drop_index('idx_user_reward_uid', table_name='user_rewards')
    op.drop_table('user_rewards')
    op.drop_index(op.f('ix_symptom_checkin_threads_uid'), table_name='symptom_checkin_threads')
    op.drop_index(op.f('ix_symptom_checkin_threads_local_date'), table_name='symptom_checkin_threads')
    op.drop_index('idx_symptom_thread_user_date', table_name='symptom_checkin_threads')
    op.drop_index('idx_symptom_thread_user_closed', table_name='symptom_checkin_threads')
    op.drop_table('symptom_checkin_threads')
    op.drop_index(op.f('ix_recommendation_schedules_uid'), table_name='recommendation_schedules')
    op.drop_index(op.f('ix_recommendation_schedules_recommendation_id'), table_name='recommendation_schedules')
    op.drop_index(op.f('ix_recommendation_schedules_id'), table_name='recommendation_schedules')
    op.drop_table('recommendation_schedules')
    op.drop_index(op.f('ix_recommendation_redistributions_uid'), table_name='recommendation_redistributions')
    op.drop_index(op.f('ix_recommendation_redistributions_recommendation_id'), table_name='recommendation_redistributions')
    op.drop_index(op.f('ix_recommendation_redistributions_original_date'), table_name='recommendation_redistributions')
    op.drop_index(op.f('ix_recommendation_redistributions_id'), table_name='recommendation_redistributions')
    op.drop_index('idx_redistribution_user_rec', table_name='recommendation_redistributions')
    op.drop_index('idx_redistribution_date', table_name='recommendation_redistributions')
    op.drop_table('recommendation_redistributions')
    op.drop_index(op.f('ix_recommendation_completions_uid'), table_name='recommendation_completions')
    op.drop_index(op.f('ix_recommendation_completions_recommendation_id'), table_name='recommendation_completions')
    op.drop_index(op.f('ix_recommendation_completions_id'), table_name='recommendation_completions')
    op.drop_index(op.f('ix_recommendation_completions_completion_date'), table_name='recommendation_completions')
    op.drop_index('idx_completion_user_date', table_name='recommendation_completions')
    op.drop_index('idx_completion_rec_date', table_name='recommendation_completions')
    op.drop_table('recommendation_completions')
    op.drop_index(op.f('ix_recommendation_advices_uid'), table_name='recommendation_advices')
    op.drop_index(op.f('ix_recommendation_advices_session_id'), table_name='recommendation_advices')
    op.drop_index(op.f('ix_recommendation_advices_id'), table_name='recommendation_advices')
    op.drop_table('recommendation_advices')
    op.drop_index(op.f('ix_mood_logs_user_id'), table_name='mood_logs')
    op.drop_index(op.f('ix_mood_logs_logged_date'), table_name='mood_logs')
    op.drop_index('idx_mood_logs_user_logged_at', table_name='mood_logs')
    op.drop_index('idx_mood_logs_user_date_unique', table_name='mood_logs')
    op.drop_table('mood_logs')
    op.drop_index(op.f('ix_conversation_summaries_user_id'), table_name='conversation_summaries')
    op.drop_index('idx_conv_summaries_user_period', table_name='conversation_summaries')
    op.drop_table('conversation_summaries')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index('idx_chat_sessions_user_status', table_name='chat_sessions')
    op.drop_index('idx_chat_sessions_last_msg', table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_care_plan_checkin_threads_uid'), table_name='care_plan_checkin_threads')
    op.drop_index(op.f('ix_care_plan_checkin_threads_local_date'), table_name='care_plan_checkin_threads')
    op.drop_index('idx_care_plan_thread_user_date', table_name='care_plan_checkin_threads')
    op.drop_index('idx_care_plan_thread_user_closed', table_name='care_plan_checkin_threads')
    op.drop_table('care_plan_checkin_threads')
    op.drop_index('uq_action_plan_user_date', table_name='action_plans', postgresql_where=sa.text('uid IS NOT NULL'))
    op.drop_index('uq_action_plan_session_date', table_name='action_plans', postgresql_where=sa.text('session_id IS NOT NULL'))
    op.drop_index(op.f('ix_action_plans_uid'), table_name='action_plans')
    op.drop_index(op.f('ix_action_plans_session_id'), table_name='action_plans')
    op.drop_index(op.f('ix_action_plans_plan_date'), table_name='action_plans')
    op.drop_index(op.f('ix_action_plans_id'), table_name='action_plans')
    op.drop_index('idx_action_plan_user_date', table_name='action_plans')
    op.drop_index('idx_action_plan_session_date', table_name='action_plans')
    op.drop_table('action_plans')
    op.drop_index(op.f('ix_weekly_checkin_questions_id'), table_name='weekly_checkin_questions')
    op.drop_index('idx_question_order', table_name='weekly_checkin_questions')
    op.drop_index('idx_question_concern', table_name='weekly_checkin_questions')
    op.drop_table('weekly_checkin_questions')
    op.drop_index(op.f('ix_user_responses_uid'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_id'), table_name='user_responses')
    op.drop_table('user_responses')
    op.drop_index(op.f('ix_user_profiles_uid'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_session_processing_status_session_id'), table_name='session_processing_status')
    op.drop_index('idx_processing_status', table_name='session_processing_status')
    op.drop_index('idx_heartbeat_at', table_name='session_processing_status')
    op.drop_table('session_processing_status')
    op.drop_index(op.f('ix_recommendation_records_uid'), table_name='recommendation_records')
    op.drop_index(op.f('ix_recommendation_records_session_id'), table_name='recommendation_records')
    op.drop_index(op.f('ix_recommendation_records_id'), table_name='recommendation_records')
    op.drop_table('recommendation_records')
    op.drop_index(op.f('ix_question_sessions_session_id'), table_name='question_sessions')
    op.drop_table('question_sessions')
    op.drop_index(op.f('ix_pubmed_cache_id'), table_name='pubmed_cache')
    op.drop_index(op.f('ix_pubmed_cache_cache_key'), table_name='pubmed_cache')
    op.drop_index('idx_pubmed_cache_key', table_name='pubmed_cache')
    op.drop_index('idx_pubmed_cache_access', table_name='pubmed_cache')
    op.drop_table('pubmed_cache')
    op.drop_index(op.f('ix_image_library_id'), table_name='image_library')
    op.drop_index('idx_image_library_usage', table_name='image_library')
    op.drop_index('idx_image_library_category', table_name='image_library')
    op.drop_table('image_library')
    # ### end Alembic commands ###
