"""add_session_id_to_recommendations

Revision ID: 20a3c53155ff
Revises: 8fd0c5f9f396
Create Date: 2025-08-20 16:46:25.365837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20a3c53155ff'
down_revision: Union[str, None] = '8fd0c5f9f396'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
