"""add_purpose_field_to_recommendations

Revision ID: 354edf1bb9fc
Revises: 20a3c53155ff
Create Date: 2025-08-20 17:41:05.502179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '354edf1bb9fc'
down_revision: Union[str, None] = '20a3c53155ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendation_records', sa.Column('purpose', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendation_records', 'purpose')
    # ### end Alembic commands ###
