"""update_recommendation_fields_to_arrays

Revision ID: 3c1e6f945f1d
Revises: 662e398ecf44
Create Date: 2025-08-19 17:56:51.944280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c1e6f945f1d'
down_revision: Union[str, None] = '662e398ecf44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendation_records', sa.Column('food_amounts', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('recommendation_records', sa.Column('food_items', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('recommendation_records', sa.Column('exercise_durations', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('recommendation_records', sa.Column('exercise_types', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('recommendation_records', sa.Column('exercise_intensities', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('recommendation_records', sa.Column('mindfulness_durations', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('recommendation_records', sa.Column('mindfulness_techniques', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('recommendation_records', 'exercise_intensity')
    op.drop_column('recommendation_records', 'food_amount')
    op.drop_column('recommendation_records', 'exercise_type')
    op.drop_column('recommendation_records', 'mindfulness_duration')
    op.drop_column('recommendation_records', 'food_item')
    op.drop_column('recommendation_records', 'exercise_duration')
    op.drop_column('recommendation_records', 'mindfulness_technique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendation_records', sa.Column('mindfulness_technique', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('recommendation_records', sa.Column('exercise_duration', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('recommendation_records', sa.Column('food_item', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('recommendation_records', sa.Column('mindfulness_duration', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('recommendation_records', sa.Column('exercise_type', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('recommendation_records', sa.Column('food_amount', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('recommendation_records', sa.Column('exercise_intensity', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('recommendation_records', 'mindfulness_techniques')
    op.drop_column('recommendation_records', 'mindfulness_durations')
    op.drop_column('recommendation_records', 'exercise_intensities')
    op.drop_column('recommendation_records', 'exercise_types')
    op.drop_column('recommendation_records', 'exercise_durations')
    op.drop_column('recommendation_records', 'food_items')
    op.drop_column('recommendation_records', 'food_amounts')
    # ### end Alembic commands ###
