"""Add primary and secondary hormone columns

Revision ID: 55ac255ddc53
Revises: 5647d1b57a23
Create Date: 2025-08-30 00:30:12.271899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55ac255ddc53'
down_revision: Union[str, None] = '5647d1b57a23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_sessions', sa.Column('primary_hormone', sa.String(length=50), nullable=True))
    op.add_column('question_sessions', sa.Column('secondary_hormones', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('user_responses', sa.Column('primary_hormone', sa.String(length=50), nullable=True))
    op.add_column('user_responses', sa.Column('secondary_hormones', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_responses', 'secondary_hormones')
    op.drop_column('user_responses', 'primary_hormone')
    op.drop_column('question_sessions', 'secondary_hormones')
    op.drop_column('question_sessions', 'primary_hormone')
    # ### end Alembic commands ###
