"""add recommendation_advices table

Revision ID: 662e398ecf44
Revises: 201294a9bf6c
Create Date: 2025-08-19 15:58:54.237568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '662e398ecf44'
down_revision: Union[str, None] = '201294a9bf6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_advices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=255), nullable=False),
    sa.Column('advice_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('recommendation_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_advices_id'), 'recommendation_advices', ['id'], unique=False)
    op.create_index(op.f('ix_recommendation_advices_recommendation_id'), 'recommendation_advices', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_recommendation_advices_uid'), 'recommendation_advices', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendation_advices_uid'), table_name='recommendation_advices')
    op.drop_index(op.f('ix_recommendation_advices_recommendation_id'), table_name='recommendation_advices')
    op.drop_index(op.f('ix_recommendation_advices_id'), table_name='recommendation_advices')
    op.drop_table('recommendation_advices')
    # ### end Alembic commands ###
