"""add session_id to action_plans

Revision ID: 78911d5faa9d
Revises: e9b5f0a13e6e
Create Date: 2026-01-08 17:05:41.208558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78911d5faa9d'
down_revision: Union[str, None] = 'e9b5f0a13e6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Update action_plan_items table
    op.add_column('action_plan_items', sa.Column('session_id', sa.String(length=255), nullable=True))
    op.alter_column('action_plan_items', 'uid',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_action_plan_items_session_id'), 'action_plan_items', ['session_id'], unique=False)

    # 2. Update action_plans table
    op.add_column('action_plans', sa.Column('session_id', sa.String(length=255), nullable=True))
    op.alter_column('action_plans', 'uid',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    
    # Update unique constraint for action_plans to allow session-based uniqueness
    op.drop_index('idx_action_plan_user_date', table_name='action_plans')
    op.create_index('idx_action_plan_user_date', 'action_plans', ['uid', 'plan_date'], unique=False)
    op.create_index('idx_action_plan_session_date', 'action_plans', ['session_id', 'plan_date'], unique=False)
    
    op.create_index(op.f('ix_action_plans_session_id'), 'action_plans', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Revert action_plans changes
    op.drop_index(op.f('ix_action_plans_session_id'), table_name='action_plans')
    op.drop_index('idx_action_plan_session_date', table_name='action_plans')
    op.drop_index('idx_action_plan_user_date', table_name='action_plans')
    op.create_index('idx_action_plan_user_date', 'action_plans', ['uid', 'plan_date'], unique=True)
    
    op.alter_column('action_plans', 'uid',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('action_plans', 'session_id')
    
    # Revert action_plan_items changes
    op.drop_index(op.f('ix_action_plan_items_session_id'), table_name='action_plan_items')
    op.alter_column('action_plan_items', 'uid',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('action_plan_items', 'session_id')
    # ### end Alembic commands ###
