"""add_family_history_and_lifestyle_fields

Revision ID: 7bddf1339f88
Revises: 0001
Create Date: 2025-08-15 15:02:27.719238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bddf1339f88'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_responses', sa.Column('family_history', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('user_responses', sa.Column('workout_intensity', sa.String(length=50), nullable=True))
    op.add_column('user_responses', sa.Column('sleep_duration', sa.String(length=50), nullable=True))
    op.add_column('user_responses', sa.Column('stress_level', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_responses', 'stress_level')
    op.drop_column('user_responses', 'sleep_duration')
    op.drop_column('user_responses', 'workout_intensity')
    op.drop_column('user_responses', 'family_history')
    # ### end Alembic commands ###
