"""add_optimal_times_field

Revision ID: 8fd0c5f9f396
Revises: 3c1e6f945f1d
Create Date: 2025-08-20 15:30:43.740566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fd0c5f9f396'
down_revision: Union[str, None] = '3c1e6f945f1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendation_records', sa.Column('optimal_times', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendation_records', 'optimal_times')
    # ### end Alembic commands ###
