"""add_survey_timezone_to_question_sessions_and_rename_timezone_to_current_timezone

Revision ID: 919a7c5c78da
Revises: 9343476943c2
Create Date: 2025-08-23 02:42:44.502485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '919a7c5c78da'
down_revision: Union[str, None] = '9343476943c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_sessions', sa.Column('survey_timezone', sa.String(length=50), nullable=True))
    op.add_column('user_responses', sa.Column('current_timezone', sa.String(length=50), nullable=True))
    op.drop_column('user_responses', 'timezone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_responses', sa.Column('timezone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('user_responses', 'current_timezone')
    op.drop_column('question_sessions', 'survey_timezone')
    # ### end Alembic commands ###
