"""add_frequency_parsed_field

Revision ID: 9d56876a1010
Revises: 354edf1bb9fc
Create Date: 2025-08-20 17:59:42.984749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d56876a1010'
down_revision: Union[str, None] = '354edf1bb9fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendation_records', sa.Column('frequency_parsed', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendation_records', 'frequency_parsed')
    # ### end Alembic commands ###
