"""add_lifestyle_focus_column

Revision ID: fe16aed4dbbb
Revises: b521a53ac247
Create Date: 2025-12-12 19:20:39.455624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe16aed4dbbb'
down_revision: Union[str, None] = 'b521a53ac247'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add lifestyle_focus column to user_profiles and user_responses tables
    # This stores user's preferred focus areas from Eat/Move/Pause selection
    op.add_column('user_profiles', sa.Column('lifestyle_focus', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('user_responses', sa.Column('lifestyle_focus', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_responses', 'lifestyle_focus')
    op.drop_column('user_profiles', 'lifestyle_focus')
    # ### end Alembic commands ###
